/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PluginsRouteImport } from './routes/plugins'
import { Route as BrowseIndexRouteImport } from './routes/browse/index'
import { Route as LibraryIndexRouteImport } from './routes/library/index'
import { Route as LibraryTitleIdRouteImport } from './routes/library/$titleId'
import { Route as BrowsePluginIdIndexRouteImport } from './routes/browse/$pluginId/index'
import { Route as BrowsePluginIdTitleIdRouteImport } from './routes/browse/$pluginId/$titleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseIndexRoute = BrowseIndexRouteImport.update({
  id: '/browse/',
  path: '/browse/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryTitleIdRoute = LibraryTitleIdRouteImport.update({
  id: '/library/$titleId',
  path: '/library/$titleId',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowsePluginIdIndexRoute = BrowsePluginIdIndexRouteImport.update({
  id: '/browse/$pluginId/',
  path: '/browse/$pluginId/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowsePluginIdTitleIdRoute = BrowsePluginIdTitleIdRouteImport.update({
  id: '/browse/$pluginId/$titleId',
  path: '/browse/$pluginId/$titleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/plugins': typeof PluginsRoute
  '/library/$titleId': typeof LibraryTitleIdRoute
  '/browse/': typeof BrowseIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/browse/$pluginId/$titleId': typeof BrowsePluginIdTitleIdRoute
  '/browse/$pluginId/': typeof BrowsePluginIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/plugins': typeof PluginsRoute
  '/library/$titleId': typeof LibraryTitleIdRoute
  '/browse': typeof BrowseIndexRoute
  '/library': typeof LibraryIndexRoute
  '/browse/$pluginId/$titleId': typeof BrowsePluginIdTitleIdRoute
  '/browse/$pluginId': typeof BrowsePluginIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/plugins': typeof PluginsRoute
  '/library/$titleId': typeof LibraryTitleIdRoute
  '/browse/': typeof BrowseIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/browse/$pluginId/$titleId': typeof BrowsePluginIdTitleIdRoute
  '/browse/$pluginId/': typeof BrowsePluginIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/plugins'
    | '/library/$titleId'
    | '/browse/'
    | '/library/'
    | '/browse/$pluginId/$titleId'
    | '/browse/$pluginId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/plugins'
    | '/library/$titleId'
    | '/browse'
    | '/library'
    | '/browse/$pluginId/$titleId'
    | '/browse/$pluginId'
  id:
    | '__root__'
    | '/'
    | '/plugins'
    | '/library/$titleId'
    | '/browse/'
    | '/library/'
    | '/browse/$pluginId/$titleId'
    | '/browse/$pluginId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PluginsRoute: typeof PluginsRoute
  LibraryTitleIdRoute: typeof LibraryTitleIdRoute
  BrowseIndexRoute: typeof BrowseIndexRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  BrowsePluginIdTitleIdRoute: typeof BrowsePluginIdTitleIdRoute
  BrowsePluginIdIndexRoute: typeof BrowsePluginIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins': {
      id: '/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/': {
      id: '/browse/'
      path: '/browse'
      fullPath: '/browse/'
      preLoaderRoute: typeof BrowseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$titleId': {
      id: '/library/$titleId'
      path: '/library/$titleId'
      fullPath: '/library/$titleId'
      preLoaderRoute: typeof LibraryTitleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/$pluginId/': {
      id: '/browse/$pluginId/'
      path: '/browse/$pluginId'
      fullPath: '/browse/$pluginId/'
      preLoaderRoute: typeof BrowsePluginIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/$pluginId/$titleId': {
      id: '/browse/$pluginId/$titleId'
      path: '/browse/$pluginId/$titleId'
      fullPath: '/browse/$pluginId/$titleId'
      preLoaderRoute: typeof BrowsePluginIdTitleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PluginsRoute: PluginsRoute,
  LibraryTitleIdRoute: LibraryTitleIdRoute,
  BrowseIndexRoute: BrowseIndexRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  BrowsePluginIdTitleIdRoute: BrowsePluginIdTitleIdRoute,
  BrowsePluginIdIndexRoute: BrowsePluginIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
